language: rust
cache: cargo
before_install:
  - sudo apt-get update
  - sudo apt-get install -y libegl1-mesa-dev libgles2-mesa-dev libsdl2-dev libsdl2-gfx-dev
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
